[package]
name = "urlencoding_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2.0.61", features = ["full", "fold"] }
urlencoding = "2.1.3"

[lib]
proc-macro = true
